# Site settings
title: Hacking data
email: clement.brutti.mairesse@gmail.com
description: Clément Brutti-Mairesse blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: clementbrutti
github_username:  clementbm
owner: Clément Brutti-Mairesse

theme: minima

paginate: 7
paginate_path: "/page/:num/"
show_excerpts: true

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
