title: Clément's blog
email: clement.brutti.mairesse@gmail.com
description: Writting some of my experiments around data chemistry
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: clementbrutti
github_username:  clementbm
owner: Clément Brutti-Mairesse
author: Clément Brutti-Mairesse

theme: minima

paginate: 7
paginate_path: "/page/:num/"
show_excerpts: true

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

google_analytics: UA-170163331-1

# Github page overrides
gist:
  noscript: false
future: true 
jailed: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
