name: CheckLinks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checklinks:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: action/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Update Rubygems
        run: 'gem update --system --no-document'
      - name: Update Bundler
        run: 'gem update bundler --no-document'
      - name: build jekyll site with drafts
        run: bundle exec jekyll build --drafts
      - name: check broken links
        run: bundle exec htmlproofer ./_site