name: CheckLinks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checklinks:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Setup Rubygems, install dependencies
        run: | 
          gem update --system --no-document
          gem update bundler --no-document
          bundle install
      - name: Build jekyll website with drafts
        run: bundle exec jekyll build --drafts
      - name: Check for broken links
        run: |
          LINK_CHECK=$(bundle exec htmlproofer --log-level :debug ./_site 2>&1)
      - name: Save and show
        run: |
          echo $LINK_CHECK
          echo $LINK_CHECK > links.log
        continue-on-error: true
      - name: Archive log links
        uses: actions/upload-artifact@v1
        with:
          name: link-check.log
          path: links.log